---
name: Release
on:
  workflow_run:
    types:
      - completed
    workflows:
      - "ci"
jobs:
  print-debug-info:
    name: Print debug info for Release workflow
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      
  get-tag:
    name: Get tag
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_branch, 'release/') }}
    outputs:
      tag: ${{ steps.get-tag-step.outputs.tag }}
    steps:
      - name: Get tag
        run: |
          branch=${{github.event.workflow_run.head_branch}}
          echo '::set-output name=tag::'${branch#release/}
        id: get-tag-step
  
  create-release:
    name: Create release
    needs: get-tag
    uses: NikitaSkrynnik/.github/.github/workflows/release.yaml@main
    with:
      tag: ${{ needs.get-tag.outputs.tag }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  release-dependent-repositories:
    name: Create release
    needs: [get-tag, create-release]
    uses: NikitaSkrynnik/.github/.github/workflows/release-dependent-repositories.yaml@main
    with:
      tag: ${{ needs.get-tag.outputs.tag }}
      dependent_repositories: |
        ["my-repo"]
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}